### ISSUE TITLE
Handle multiple file upload

### ISSUE THREAD

**Issue by jelosh** [RohanImmanuel/NightwatchJS-Remote-File-Upload#1]
This custom command works great, thanks for posting!
Any chance you can tweak it to accept multiple files in the upload (filePath) request?

**Comment by RohanImmanuel** [comment]
@jelosh the custom command already allows for this

Give this a try
```
browser
.UploadLocalFile("/path_to_file/testfileOne.txt", "#file-upload")
.UploadLocalFile("/path_to_file/testfileTwo.txt", "#file-upload")
```

**Comment by jelosh** [comment]
@RohanImmanuel - thanks, while that makes sense, sadly our app is looking for 2 files as part of a single upload and will fail without. Ideally if we could pass an array of files as the first parameter it would be awesome, something like: 
`.uploadLocalFile([filePath1, filePath2], 'input[type=file]')`

**Comment by RohanImmanuel** [comment]
@jelosh, you might have to fork the repo and run this section twice, once for each file:
https://github.com/RohanImmanuel/NightwatchJS-Remote-File-Upload/blob/master/customCommands/UploadLocalFile.js#L5-L24

then save the temporary paths provided and send them together here:
https://github.com/RohanImmanuel/NightwatchJS-Remote-File-Upload/blob/master/customCommands/UploadLocalFile.js#L54
